# Default values for file integrity operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# to add tolerations, set custom_tolerations to true and use the following format:
# tolerations:
#   - key: "node1"
#     operator: "Exists"
#     effect: "NoSchedule"
#   - key: "node2"
#     operator: "Exists"
#     effect: "NoSchedule"

fio:
  name: file-integrity-operator
  namespace: openshift-file-integrity
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: stable
  config:
    enable: false
    name: "ChangeMe"
    key: "ChangeMe"
    gracePeriod: 20 
    maxBackups: 5 
    initialDelay: 60 
  debug: false
  custom_tolerations: false
 