apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
 name: console-banner
spec:
 # Banner Text:
 text: "Pivot OpenShift {{ upper .Values.cluster_name }}"
 # Other options are BannerBottom, BannerTopBottom
 location: {{ .Values.location }}
 # Hexcode for text color
 color: "{{ .Values.text_color }}"
 # Hexcode for banner background color
 backgroundColor: "{{ .Values.background_color }}"