apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: {{ .Values.amq_broker.name }}
spec:
  acceptors:
    - name: artemis
      expose: true
      protocols: 'amqp,core,stomp'
      port: 61617
      sslEnabled: true
      sslSecret: {{ .Values.amq_broker.sslSecret }}
  adminUser: {{ .Values.amq_broker.admin_user }}
  adminPassword: {{ .Values.amq_broker.admin_pass }}
  console:
      expose: true
      sslEnabled: true
      sslSecret: {{ .Values.amq_broker.acceptor_sslSecret }}
  deploymentPlan:
    size: 1
    image: {{ .Values.amq_broker.image }}
    journalType: aio
    persistenceEnabled: true
    messageMigration: true
    requireLogin: true
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    storage:
      size: 25Gi