---
# tasks file for create-standalone

- name: Set argo apps name
  ansible.builtin.set_fact:
    metadata_name: !unsafe '{{ path.basename }}'
  no_log: true

- name: Set source Path
  ansible.builtin.set_fact:
    source_path: !unsafe '{{ path }}'
  no_log: true

- name: Include env vars
  include_vars: "vars/main.yml"

- name: Include vault vars
  include_vars: ../configs.yml

- name: Create configmap
  kubernetes.core.k8s:
    host: '{{ cluster_url }}'
    api_key: '{{ api_token }}'
    verify_ssl: false
    state: present
    definition: "{{ lookup('template', 'gitops-cm.yml.j2') }}"
    apply: true

- name: Create application
  kubernetes.core.k8s:
    host: '{{ cluster_url }}'
    api_key: '{{ api_token }}'
    verify_ssl: false
    state: present
    definition: "{{ lookup('template', 'app.yml.j2') }}"
    apply: true