---
- name: Set argo apps name
  ansible.builtin.set_fact:
    metadata_name: !unsafe '{{ path.basename }}'
  no_log: true

- name: Set source Path
  ansible.builtin.set_fact:
    source_path: !unsafe '{{ path }}'
  no_log: true

- name: Set env fact
  ansible.builtin.set_fact:
    cluster_env: "{{ item }}"
  when: item is defined

- name: Set env fact
  ansible.builtin.set_fact:
    cluster_env: "{{ env }}"
  when: env != "all"

- name: Fetch env vars
  include_vars: "vars/{{ cluster_env }}/main.yml"

- name: Create applicationset
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argo/appset.yml.j2') }}"
    apply: true
  when: git_branch == "main"
