{{ if .Values.install_central }}
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: {{ .Values.central_name }}
  namespace: {{ .Values.central_namespace }}
  labels:
    pivot: rhacs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    meta.helm.sh/release-namespace: {{ .Values.central_namespace }}
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: {{ .Values.central_name }}
spec:
  central:
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
      resources:
        limits:
          cpu: {{ .Values.central_db.limits.cpu }}
          memory: {{ .Values.central_db.limits.memory }}
        requests:
          cpu: {{ .Values.central_db.requests.cpu }}
          memory: {{ .Values.central_db.requests.memory }}
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
        host: {{ .Values.central_route }}
    persistence:
      persistentVolumeClaim:
        claimName: {{ .Values.central_claimname }}
        storageClassName: {{ .Values.central_storageclass }}
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScaling: {{ .Values.scanner.autoscaling }}
        maxReplicas: {{ .Values.scanner.maxreplicas }}
        minReplicas: {{ .Values.scanner.minreplicas }}
        replicas: {{ .Values.scanner.minreplicas }}
    scannerComponent: {{ .Values.scanner.scannercomponent }}
{{ end }}