apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: {{ .Values.installPlanApproval }}
  name: {{ .Values.name }}
  source: {{ .Values.source }}
  sourceNamespace: {{ .Values.sourceNamespace }}