apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: no-priv-policy
  namespace: open-cluster-management
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-4 Information In Shared Resources
    policy.open-cluster-management.io/standards: DOD STIG
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-podsecuritypolicy
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: policy/v1beta1
                kind: PodSecurityPolicy
                metadata:
                  annotations:
                    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
                  name: sample-restricted-psp
                spec:
                  seLinux:
                    rule: RunAsAny
                  hostPID: false
                  hostNetwork: true
                  runAsUser:
                    rule: RunAsAny
                  hostPorts:
                    - max: 65535
                      min: 1000
                  fsGroup:
                    rule: RunAsAny
                  privileged: false
                  hostIPC: false
                  supplementalGroups:
                    rule: RunAsAny
                  volumes:
                    - '*'
                  allowPrivilegeEscalation: false
                  allowedCapabilities:
                    - '*'
          pruneObjectBehavior: None
          remediationAction: inform
          severity: high
  remediationAction: inform