---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.templates.override_cm . }}
data:
  {{- (.Files.Glob "scripts-override/**.sh").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.templates.config_cm . }}
data:
  {{ tpl (.Files.Glob "conf/**").AsConfig . | nindent 2 }}