{{- if and (eq .Values.kind "Deployment") (.Values.application.persistent) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.templates.pvc_name . }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.application.volume_capacity }}
  storageClassName: "{{ .Values.application.storageclass }}"
{{- end }}
