apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: restricted-ssc
  namespace: open-cluster-management
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-4 Information In Shared Resources
    policy.open-cluster-management.io/standards: DOD STIG
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-securitycontextconstraints
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                allowHostPorts: false
                requiredDropCapabilities:
                  - KILL
                  - MKNOD
                  - SETUID
                  - SETGID
                allowPrivilegedContainer: false
                runAsUser:
                  type: MustRunAsRange
                users: []
                allowHostDirVolumePlugin: false
                allowHostIPC: false
                seLinuxContext:
                  type: MustRunAs
                readOnlyRootFilesystem: false
                metadata:
                  annotations:
                    kubernetes.io/description: >-
                      restricted denies access to all host features and requires
                      pods to be run with a UID, and SELinux context that are
                      allocated to the namespace.  This is the most restrictive
                      SCC and it is used by default for authenticated users.
                  name: restricted
                fsGroup:
                  type: MustRunAs
                groups:
                  - 'system:authenticated'
                kind: SecurityContextConstraints
                supplementalGroups:
                  type: RunAsAny
                volumes:
                  - configMap
                  - downwardAPI
                  - emptyDir
                  - persistentVolumeClaim
                  - projected
                  - secret
                allowHostPID: false
                allowHostNetwork: false
                allowPrivilegeEscalation: true
                apiVersion: security.openshift.io/v1
          pruneObjectBehavior: None
          remediationAction: inform
          severity: high
  remediationAction: inform
