kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.central_cert_secret_name }}
  namespace: {{ .Values.central_namespace }}
data:
  tls.crt: >-
    {{ .Values.acs_cert }}
  tls.key: >-
    {{ .Values.acs_key }}
type: kubernetes.io/tls