{{- if eq .Values.platform "openshift" }}
{{- $svc_name := tpl .Values.templates.service . }}
{{- $app_name := tpl .Values.application.name . }}
{{- $route_name := tpl .Values.templates.route . }}
{{- $jolokia_ssl := and (.Values.parameters.tls_enabled) (.Values.parameters.jolokia_passthrough) }}
{{- range .Values.service.console }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: {{ $app_name }}
  name: {{ $route_name }}-console
spec:
  {{- if $.Values.parameters.append_ns }}
  host: {{ $route_name }}.{{ $.Release.Namespace }}.{{ $.Values.parameters.openshift_appdomain }}
  {{- else }}
  host: {{ $route_name }}.{{ $.Values.parameters.openshift_appdomain }}
  {{- end }}
  to:
    kind: Service
    name: {{ $svc_name }}
  port:
    targetPort: {{ .port }}
  tls:
{{- if $jolokia_ssl }}
    termination: passthrough
{{- else }}
    termination: edge
{{- end }}
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
{{- if not .Values.clustered }}
{{- if .Values.passthrough_route.enabled }}
{{- range .Values.service.acceptors }}
{{- $nm := toString .name }}
{{- if eq $nm $.Values.passthrough_route.service }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: {{ $app_name }}
  name: {{ $route_name }}-passthrough
spec:
  {{- if $.Values.parameters.append_ns }}
  host: {{ $.Values.passthrough_route.hostname }}.{{ $.Release.Namespace }}.{{ $.Values.parameters.openshift_appdomain }}
  {{- else }}
  host: {{ $.Values.passthrough_route.hostname }}.{{ $.Values.parameters.openshift_appdomain }}
  {{- end }}
  to:
    kind: Service
    name: {{ $svc_name }}
  port:
    targetPort: {{ .port }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
